// Список файлов с практиками сайта (из этой папки).
// Чтобы добавить практику: положите файл в папку practices/ и допишите его имя сюда.
Trainer.load([
  'english-past-simple.js',
  'english-vocabulary.js',
  'math-algebra.js',
  'physics-kinematics.js',
  'python-basics.js',
  'javascript-basics.js',
  'java-01-basics.js',
  'java-02-control.js',
  'java-03-arrays-strings.js',
  'java-04-methods.js',
  'java-05-classes.js',
  'java-06-encapsulation.js',
  'java-07-static-final.js',
  'java-08-inheritance.js',
  'java-09-polymorphism.js',
  'java-10-abstraction.js',
  'java-11-object-methods.js',
  'java-12-nested-enums.js',
  'java-13-exceptions.js',
  'java-14-generics-collections.js',
  'java-15-oop-design.js',
  'java-16-final-test.js',
]);
